@startuml
/'
Copyright 2017-2018 Government of Canada - Public Services and Procurement Canada - buyandsell.gc.ca

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'/

skinparam ParticipantPadding 20
skinparam BoxPadding 20

title Key Rotation Sequence

box "Indy" #LightBlue
    participant "Ledger" as ledger
endbox

box "VON Anchor" #Linen
    actor "Anchor" as an
    actor "Wallet" as wallet
endbox

actor "Actuator" as ator

=== KEY ROTATION SEQUENCE ==
note over ledger, ator
    All VON anchor service wrapper APIs are up
    VON public DID is on ledger
endnote

ator -> an: call reseed(next seed)
an -> wallet: call reseed_init(next seed)
wallet --> an: new verification key
an -> ledger: get nym role
ledger --> an: current role
an -> ledger: update nym on current role
ledger --> an:
an -> wallet: call reseed_apply()
wallet -> wallet: update seed, seed-to-DID metadata, verification key
wallet --> an:
an --> ator:

@enduml
